language: node_js
node_js:
  - 'stable'
before_install:
  - 'nvm install-latest-npm'
script:
  - npm run test -- --coverage --no-cache
after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
